<<<<<<< HEAD
# Generated by Django 2.2.3 on 2019-07-25 11:21
=======
# Generated by Django 2.2.3 on 2019-07-25 11:23
>>>>>>> 2800f3406266d6710ec34501936b8f22c99c8c17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Masukan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=225)),
                ('alamat_email', models.CharField(max_length=225)),
                ('judul', models.CharField(max_length=100)),
                ('isi_pesan', models.TextField()),
=======
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
>>>>>>> 2800f3406266d6710ec34501936b8f22c99c8c17
            ],
        ),
    ]
