# Generated by Django 2.2.3 on 2019-07-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokowi_center', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Masukan',
        ),
    ]
