# Generated by Django 2.2.3 on 2019-07-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokowi_center', '0002_delete_masukan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masukan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=225)),
                ('alamat_email', models.CharField(max_length=225)),
                ('judul', models.CharField(max_length=100)),
                ('isi_pesan', models.TextField()),
            ],
        ),
    ]
